<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $table = 'posts';

    public function seo(){
        return $this->hasOne(Seo::class, "post_id", "id");
    }

    public static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($post){
            $post->seo->delete();
        });
    }
}
